Make by **was making** in 2008
1. Series
2. Dataframe
3. panel

Padas in open source Python library for data manipulation and analysis. it was created by Wes Mckinnet in 2008 to effciently work with structured and tabular data. it provides powerfull data structures such as Series and Dataframe, making data cleaning , transformation and analysis easie.

A Series is a one-dimensional labeled array that is capable of holding data of any type.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
import numpy as np

In [ ]:
s= pd.Series()
print(s)

Series([], dtype: object)

In [ ]:
s=pd.Series(data=[1,2,3],index=["a","b","c"])

In [ ]:
dic= {"a":100,"b":200,"c":300}
d=pd.Series(data=dic)

In [ ]:
index=["a","b","c","d"]
print(d)

a    100
b    200
c    300
dtype: int64

In [ ]:
dic={"a":100,"b":200,"c":300,"d":400}
d=pd.Series(data=dic,index=["a","b","c"])
print(d)

a    100
b    200
c    300
dtype: int64

In [ ]:
i = np.array(["a","b","c"])
d = np.arange(1,4)
se=pd.Series(data=d,index=i)
print(se)

a    1
b    2
c    3
dtype: int64

In [ ]:
s=pd.Series(d=5,index=["a","b","c"])
print(s)

TypeError: Series.__init__() got an unexpected keyword argument 'd'

In [ ]:
l=[]
d=[]
for i in range(1,5):
  d.append(i)
  l.append(chr(64+i))
s= pd.Series(data=d,index=l)
print(s)

A    1
B    2
C    3
D    4
dtype: int64

2. DataFrame

A DataFrame is a two-dimensional or multi-dimensional data structure. Data is aligned in a tabular format that contains rows and columns.

In [ ]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [ ]:
df

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
data =[1,2,3,4,5]
df=pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4
4  5

In [ ]:
data = [["i","ii","iii"],["anvar","Shashi","nisha"],[23,22,21]]
a=data[1][1]
print(a)
c=data[0][1],data[1][1],data[2][1]
print(c)
# c.append(data[0][0])
# c.append(data[1][0])
# c.append(data[2][1])
# print(c)

Shashi
('ii', 'Shashi', 22)

In [ ]:
name =["anver","Shashi","krit","shreaya","sushant","nisha"]
py=[45,67,43,23,65,12]
ml=[23,54,34,54,24,25]
d=pd.DataFrame(data=[name,py,ml])
print(d)

       0       1     2        3        4      5
0  anver  Shashi  krit  shreaya  sushant  nisha
1     45      67    43       23       65     12
2     23      54    34       54       24     25

In [ ]:
dic ={"name":name,"py":py,"ml":ml}
d=pd.DataFrame(data=dic)
print(d)

      name  py  ml
0    anver  45  23
1   Shashi  67  54
2     krit  43  34
3  shreaya  23  54
4  sushant  65  24
5    nisha  12  25

In [ ]:
d[d.name=="nisha"]

    name  py  ml
5  nisha  12  25

In [ ]:
data ={
    "One":pd.Series([1,2,3],index=["a","b","c"]),
    "Two":pd.Series([1,2,3,4],index=["a","b","c","d"])
}
df=pd.DataFrame(data)
print(df)

   One  Two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [ ]:
df = pd.DataFrame(np.arange(1,7).reshape(2,3), columns = ["col1","col2","col3"])
print(df)

   col1  col2  col3
0     1     2     3
1     4     5     6

In [2]:
df = pd.read_table("/content/chiporders.tsv")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [8]:
col = ["sr.no","city","coaching center","course", "state", "course duration"]
df = pd.read_table("/content/course.csv", sep=",", header=None, names=col)
df

,sr.no,city,coaching center,course,state,course duration
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months
2,3,Bengaluru,MNO institute .Ltd,Data Science,TN,11 Months
3,4,Bhopal,RST institute .Pvt.LTD,ML,MP,3 Months
4,5,Mumbai,EFG institute .Pvt.LTD,DL,MH,3 Months
5,6,Hyderabad,LMN institute,Could,AP,4 Months
6,7,Patna,DEF institute .Ltd,Web Serv,BH,4 Months
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months
10,11,Bhopal,IJK institute,DL,MP,3 Months
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months
16,17,Delhi,WXY institute,AWS,UP,3 Months
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months
20,21,Surat,INS institute,Data Science,Gj,11 Months
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months
23,24,Channai,MTK institute,Could,KT,4 Months
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months

In [3]:
df_2 = pd.read_table("/content/psd.user", sep="|")
df_2

       1  24  M     technician  85711
0      2  53  F          other  94043
1      3  23  M         writer  32067
2      4  24  M     technician  43537
3      5  33  F          other  15213
4      6  42  M      executive  98101
..   ...  .. ..            ...    ...
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

[942 rows x 5 columns]

In [ ]:
df_2.head(10)

    1  24  M     technician  85711
0   2  53  F          other  94043
1   3  23  M         writer  32067
2   4  24  M     technician  43537
3   5  33  F          other  15213
4   6  42  M      executive  98101
5   7  57  M  administrator  91344
6   8  36  M  administrator  05201
7   9  29  M        student  01002
8  10  53  M         lawyer  90703
9  11  39  F          other  30329

In [4]:
dx = pd.read_excel("/content/exbook.xlsx")
print("head row \n")
dx.head(10)

head row

,Sr.NO,Books,Author,year,Price,Profit
0,1,The Discovery of India,Jawaharlal Nehru,1946,599.95,0.30
1,2,The Story of my Experiments with Truth,Mahatma Gandhi,1927,159.00,0.30
2,3,Glimps of World History,J.Nehru,1934,750.46,0.24
3,4,A Guide to Health,Mahatma Gandhi,1921,250.00,0.25
4,5,Ignited Minds,APJ Abdul Kalam,2002,300.00,0.10
5,6,Wings of Fire,APJ Abdul Kalam,1999,1275.25,0.10

In [ ]:
print("tail row \n")
dx.tail(10)

tail row

,Sr.NO,Books,Author,year,Price,Profit
0,1,The Discovery of India,Jawaharlal Nehru,1946,599.95,0.30
1,2,The Story of my Experiments with Truth,Mahatma Gandhi,1927,159.00,0.30
2,3,Glimps of World History,J.Nehru,1934,750.46,0.24
3,4,A Guide to Health,Mahatma Gandhi,1921,250.00,0.25
4,5,Ignited Minds,APJ Abdul Kalam,2002,300.00,0.10
5,6,Wings of Fire,APJ Abdul Kalam,1999,1275.25,0.10

In [ ]:
col = ["sr_no","age","gender","jobs","pincode"]
df = pd.read_table("/content/psd.user", sep="|", header=None, names=col)
df

     sr_no  age gender           jobs pincode
0        1   24      M     technician   85711
1        2   53      F          other   94043
2        3   23      M         writer   32067
3        4   24      M     technician   43537
4        5   33      F          other   15213
..     ...  ...    ...            ...     ...
938    939   26      F        student   33319
939    940   32      M  administrator   02215
940    941   20      M        student   97229
941    942   48      F      librarian   78209
942    943   22      M        student   77841

[943 rows x 5 columns]

In [9]:
df.city.head()

0       Mumbai
1        Delhi
2    Bengaluru
3       Bhopal
4       Mumbai
Name: city, dtype: object

In [10]:
df.course.tail()

20    Data Science
21              ML
22              DL
23           Could
24        Web Serv
Name: course, dtype: object

In [11]:
df['coaching center'].head(10)

0         PQR institute .Pvt
1     ABC institute .Pvt.LTD
2        MNO  institute .Ltd
3    RST  institute .Pvt.LTD
4    EFG  institute .Pvt.LTD
5            LMN  institute
6       DEF   institute .Ltd
7    PQR  institute .Pvt.LTD
8        UVW  institute .Ltd
9       GHI   institute .Ltd
Name: coaching center, dtype: object

In [12]:
df[['city','course','coaching center', 'state']].head(10)

        city        course          coaching center state
0     Mumbai            BI       PQR institute .Pvt    MH
1      Delhi            AI   ABC institute .Pvt.LTD    UP
2  Bengaluru  Data Science      MNO  institute .Ltd    TN
3     Bhopal            ML  RST  institute .Pvt.LTD    MP
4     Mumbai            DL  EFG  institute .Pvt.LTD    MH
5  Hyderabad         Could          LMN  institute     AP
6      Patna      Web Serv     DEF   institute .Ltd    BH
7    Channai           AWS  PQR  institute .Pvt.LTD    KT
8    Kolkata    Networking      UVW  institute .Ltd    WB
9  Hyderabad            AI     GHI   institute .Ltd    AP

In [13]:
df[['sr.no','coaching center','course']].head(10)

   sr.no          coaching center        course
0      1       PQR institute .Pvt            BI
1      2   ABC institute .Pvt.LTD            AI
2      3      MNO  institute .Ltd  Data Science
3      4  RST  institute .Pvt.LTD            ML
4      5  EFG  institute .Pvt.LTD            DL
5      6          LMN  institute          Could
6      7     DEF   institute .Ltd      Web Serv
7      8  PQR  institute .Pvt.LTD           AWS
8      9      UVW  institute .Ltd    Networking
9     10     GHI   institute .Ltd            AI

In [14]:
df.city +", "+ df['state']

0        Mumbai, MH
1         Delhi, UP
2     Bengaluru, TN
3        Bhopal, MP
4        Mumbai, MH
5     Hyderabad, AP
6         Patna, BH
7       Channai, KT
8       Kolkata, WB
9     Hyderabad, AP
10       Bhopal, MP
11         Pune, MH
12        Delhi, UP
13       Mumbai, MH
14        Patna, BH
15        Surat, GJ
16        Delhi, UP
17       Mumbai, MH
18         Pune, MH
19    Bengaluru, TN
20        Surat, Gj
21    Hyderabad, AP
22       Mumbai, MH
23      Channai, KT
24        Patna, BH
dtype: object

In [16]:
df['loction']=df.city +", "+ df['state']
df

,sr.no,city,coaching center,course,state,course duration,loction
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months,"Mumbai, MH"
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months,"Delhi, UP"
2,3,Bengaluru,MNO institute .Ltd,Data Science,TN,11 Months,"Bengaluru, TN"
3,4,Bhopal,RST institute .Pvt.LTD,ML,MP,3 Months,"Bhopal, MP"
4,5,Mumbai,EFG institute .Pvt.LTD,DL,MH,3 Months,"Mumbai, MH"
5,6,Hyderabad,LMN institute,Could,AP,4 Months,"Hyderabad, AP"
6,7,Patna,DEF institute .Ltd,Web Serv,BH,4 Months,"Patna, BH"
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months,"Channai, KT"
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months,"Kolkata, WB"
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months,"Hyderabad, AP"
10,11,Bhopal,IJK institute,DL,MP,3 Months,"Bhopal, MP"
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months,"Pune, MH"
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months,"Delhi, UP"
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months,"Mumbai, MH"
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months,"Patna, BH"
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months,"Surat, GJ"
16,17,Delhi,WXY institute,AWS,UP,3 Months,"Delhi, UP"
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months,"Mumbai, MH"
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months,"Pune, MH"
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months,"Bengaluru, TN"
20,21,Surat,INS institute,Data Science,Gj,11 Months,"Surat, Gj"
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months,"Hyderabad, AP"
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months,"Mumbai, MH"
23,24,Channai,MTK institute,Could,KT,4 Months,"Channai, KT"
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months,"Patna, BH"

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sr.no            25 non-null     int64
 1   city             25 non-null     object
 2   coaching center  25 non-null     object
 3   course           25 non-null     object
 4   state            25 non-null     object
 5   course duration  25 non-null     object
 6   loction          25 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.5+ KB

#when i create a new columns that it returns datatype ***objects***

In [32]:
df['coaching deatil']=df['coaching center'] +" | "+ df['state'] +" \ "+df['course duration']
df

,sr.no,city,coaching center,course,state,course duration,coaching deatil
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months,PQR institute .Pvt | MH \ 9 Months
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months,ABC institute .Pvt.LTD | UP \ 18 Months
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months,PQR institute .Pvt.LTD | KT \ 3 Months
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months,UVW institute .Ltd | WB \ 3 Months
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months,GHI institute .Ltd | AP \ 18 Months
10,11,Bhopal,IJK institute,DL,MP,3 Months,IJK institute | MP \ 3 Months
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months,KLM institute .Ltd | MH \ 11 Months
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months,STU institute .Ltd | UP \ 6 Months
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months,XYZ institute .Pvt.LTD | MH \ 3 Months
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months,NOP institute .Ltd | BH \ 3 Months
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months,QRS institute .Ltd | GJ \ 3 Months
16,17,Delhi,WXY institute,AWS,UP,3 Months,WXY institute | UP \ 3 Months
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months,ZAB institute | MH \ 4 Months
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months,CDE institute .Ltd | MH \ 11 Months
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months,JKL institute .Pvt.LTD | TN \ 18 Months
20,21,Surat,INS institute,Data Science,Gj,11 Months,INS institute | Gj \ 11 Months
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months,ZAP institute .Ltd | AP \ 3 Months
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months,XCAD institute .Pvt.LTD | MH \ 3 Months
23,24,Channai,MTK institute,Could,KT,4 Months,MTK institute | KT \ 4 Months
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months,BST institute .Ltd | BH \ 4 Months

In [25]:
df.drop("coaching deatil",axis=1,inplace=True)
df

,sr.no,city,coaching center,course,state,course duration,loction
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months,"Mumbai, MH"
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months,"Delhi, UP"
2,3,Bengaluru,MNO institute .Ltd,Data Science,TN,11 Months,"Bengaluru, TN"
3,4,Bhopal,RST institute .Pvt.LTD,ML,MP,3 Months,"Bhopal, MP"
4,5,Mumbai,EFG institute .Pvt.LTD,DL,MH,3 Months,"Mumbai, MH"
5,6,Hyderabad,LMN institute,Could,AP,4 Months,"Hyderabad, AP"
6,7,Patna,DEF institute .Ltd,Web Serv,BH,4 Months,"Patna, BH"
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months,"Channai, KT"
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months,"Kolkata, WB"
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months,"Hyderabad, AP"
10,11,Bhopal,IJK institute,DL,MP,3 Months,"Bhopal, MP"
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months,"Pune, MH"
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months,"Delhi, UP"
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months,"Mumbai, MH"
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months,"Patna, BH"
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months,"Surat, GJ"
16,17,Delhi,WXY institute,AWS,UP,3 Months,"Delhi, UP"
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months,"Mumbai, MH"
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months,"Pune, MH"
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months,"Bengaluru, TN"
20,21,Surat,INS institute,Data Science,Gj,11 Months,"Surat, Gj"
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months,"Hyderabad, AP"
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months,"Mumbai, MH"
23,24,Channai,MTK institute,Could,KT,4 Months,"Channai, KT"
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months,"Patna, BH"

In [28]:
df.drop(["coaching deatil",'loction'],axis=1,inplace=True)
df

,sr.no,city,coaching center,course,state,course duration
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months
2,3,Bengaluru,MNO institute .Ltd,Data Science,TN,11 Months
3,4,Bhopal,RST institute .Pvt.LTD,ML,MP,3 Months
4,5,Mumbai,EFG institute .Pvt.LTD,DL,MH,3 Months
5,6,Hyderabad,LMN institute,Could,AP,4 Months
6,7,Patna,DEF institute .Ltd,Web Serv,BH,4 Months
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months
10,11,Bhopal,IJK institute,DL,MP,3 Months
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months
16,17,Delhi,WXY institute,AWS,UP,3 Months
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months
20,21,Surat,INS institute,Data Science,Gj,11 Months
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months
23,24,Channai,MTK institute,Could,KT,4 Months
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months

In [29]:
df.drop(2,axis=0,inplace=True)
df

,sr.no,city,coaching center,course,state,course duration
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months
3,4,Bhopal,RST institute .Pvt.LTD,ML,MP,3 Months
4,5,Mumbai,EFG institute .Pvt.LTD,DL,MH,3 Months
5,6,Hyderabad,LMN institute,Could,AP,4 Months
6,7,Patna,DEF institute .Ltd,Web Serv,BH,4 Months
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months
10,11,Bhopal,IJK institute,DL,MP,3 Months
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months
16,17,Delhi,WXY institute,AWS,UP,3 Months
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months
20,21,Surat,INS institute,Data Science,Gj,11 Months
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months
23,24,Channai,MTK institute,Could,KT,4 Months
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months

In [31]:
df.drop([6,3,4,5],axis=0,inplace=True)
df

,sr.no,city,coaching center,course,state,course duration
0,1,Mumbai,PQR institute .Pvt,BI,MH,9 Months
1,2,Delhi,ABC institute .Pvt.LTD,AI,UP,18 Months
7,8,Channai,PQR institute .Pvt.LTD,AWS,KT,3 Months
8,9,Kolkata,UVW institute .Ltd,Networking,WB,3 Months
9,10,Hyderabad,GHI institute .Ltd,AI,AP,18 Months
10,11,Bhopal,IJK institute,DL,MP,3 Months
11,12,Pune,KLM institute .Ltd,Data Science,MH,11 Months
12,13,Delhi,STU institute .Ltd,BI,UP,6 Months
13,14,Mumbai,XYZ institute .Pvt.LTD,Could,MH,3 Months
14,15,Patna,NOP institute .Ltd,AWS,BH,3 Months
15,16,Surat,QRS institute .Ltd,ML,GJ,3 Months
16,17,Delhi,WXY institute,AWS,UP,3 Months
17,18,Mumbai,ZAB institute,Web Serv,MH,4 Months
18,19,Pune,CDE institute .Ltd,Data Science,MH,11 Months
19,20,Bengaluru,JKL institute .Pvt.LTD,AI,TN,18 Months
20,21,Surat,INS institute,Data Science,Gj,11 Months
21,22,Hyderabad,ZAP institute .Ltd,ML,AP,3 Months
22,23,Mumbai,XCAD institute .Pvt.LTD,DL,MH,3 Months
23,24,Channai,MTK institute,Could,KT,4 Months
24,25,Patna,BST institute .Ltd,Web Serv,BH,4 Months

#Setting a indexing

In [35]:
col = ["sr.no","city","coaching center","course", "state", "course duration"]
df = pd.read_table("/content/course.csv", sep=",", header=None, names=col)

In [38]:
df.set_index("course",inplace=True)
df.head()

              sr.no       city           coaching center state course duration
course
BI                1     Mumbai        PQR institute .Pvt    MH        9 Months
AI                2      Delhi    ABC institute .Pvt.LTD    UP       18 Months
Data Science      3  Bengaluru       MNO  institute .Ltd    TN       11 Months
ML                4     Bhopal   RST  institute .Pvt.LTD    MP        3 Months
DL                5     Mumbai   EFG  institute .Pvt.LTD    MH        3 Months
Could             6  Hyderabad           LMN  institute     AP        4 Months
Web Serv          7      Patna      DEF   institute .Ltd    BH        4 Months
AWS               8    Channai   PQR  institute .Pvt.LTD    KT        3 Months
Networking        9    Kolkata       UVW  institute .Ltd    WB        3 Months
AI               10  Hyderabad      GHI   institute .Ltd    AP       18 Months
DL               11     Bhopal          IJK   institute     MP        3 Months
Data Science     12       Pune      KLM   institute .Ltd    MH       11 Months
BI               13      Delhi       STU  institute .Ltd    UP        6 Months
Could            14     Mumbai   XYZ  institute .Pvt.LTD    MH        3 Months
AWS              15      Patna       NOP  institute .Ltd    BH        3 Months
ML               16      Surat       QRS  institute .Ltd    GJ        3 Months
AWS              17      Delhi           WXY  institute     UP        3 Months
Web Serv         18     Mumbai          ZAB   institute     MH        4 Months
Data Science     19       Pune       CDE  institute .Ltd    MH       11 Months
AI               20  Bengaluru   JKL  institute .Pvt.LTD    TN       18 Months
Data Science     21      Surat           INS   institute    Gj       11 Months
ML               22  Hyderabad       ZAP  institute .Ltd    AP        3 Months
DL               23     Mumbai  XCAD  institute .Pvt.LTD    MH        3 Months
Could            24    Channai          MTK   institute     KT        4 Months
Web Serv         25      Patna       BST  institute .Ltd    BH        4 Months

#Reseting indexing

In [41]:
df.index.name='course'
# df.reset_index(inplace=True)
df.head()

,course,sr.no,city,coaching center,state,course duration
course,,,,,,
0,BI,1,Mumbai,PQR institute .Pvt,MH,9 Months
1,AI,2,Delhi,ABC institute .Pvt.LTD,UP,18 Months
2,Data Science,3,Bengaluru,MNO institute .Ltd,TN,11 Months
3,ML,4,Bhopal,RST institute .Pvt.LTD,MP,3 Months
4,DL,5,Mumbai,EFG institute .Pvt.LTD,MH,3 Months

In [42]:
class Raj():
  pass
obj=Raj()
type(obj)

__main__.Raj

#how many methon in pandas

In [44]:
df.dtypes

course             object
sr.no               int64
city               object
coaching center    object
state              object
course duration    object
dtype: object

In [45]:
df.shape

(25, 6)

In [48]:
df.columns

Index(['course', 'sr.no', 'city', 'coaching center', 'state',
       'course duration'],
      dtype='object')

In [49]:
df.size

150