### **PANDAS**

We learned NumPy —

Which helped us work with numerical data using arrays.

But real-world data is not just numbers… it comes in tables (rows & columns)

**That’s where today’s topic comes in — Pandas**

### **Definition**

Pandas is a Python library used for data analysis and data manipulation

Pandas = working with data in table format

### **Application of Pandas**

1)Data cleaning

2)Data analysis

3)Handling CSV / Excel files

4)Data preprocessing for ML

5)Business reporting

### **IMPORTING PANDAS**

In [ ]:
import pandas as pd

pd is just a short name for pandas

### **READING DATA (VERY IMPORTANT)**

CLICK ON THIS LINK FOR DATASETS: [Dataset](https://docs.google.com/spreadsheets/d/1NwZZvF_J8dBH6kDAE0MYRyfxBok36yTAaq-aTzNA9HE/edit?usp=sharing)

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")

In [ ]:
df = pd.read_excel("/content/Dataset.xlsx")

### **VIEWING DATA**

In [ ]:
df.head() #display first 5 value

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5

In [ ]:
df.head(10) #displayt first 10 value

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
5,6,Student_6,Female,Chennai,BTech,Maths,NaN,83,4.9,6,6
6,7,Student_7,Male,Bangalore,BCom,Maths,NaN,75,4.6,5,7
7,8,Student_8,Male,Chennai,BCom,Computer,NaN,63,3.9,1,8
8,9,Student_9,Male,Bangalore,BTech,Computer,NaN,97,1.1,3,9
9,10,Student_10,Female,Bangalore,BBA,English,NaN,86,2.8,5,10

In [ ]:
df.tail() #display last 5 value

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

In [ ]:
df.tail(10) #display last 10 value

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
990,991,Student_991,Female,Bangalore,BTech,Computer,92.0,60,5.1,1,991
991,992,Student_992,Female,Delhi,BBA,Economics,47.0,78,1.4,6,992
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,6,993
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

### **CHECKING STRUCTURE OF DATASET**

In [ ]:
df.shape #show case the len of coloum and rows

(1000, 11)

In [ ]:
df.columns #show all coloum name

Index(['Student_ID', 'Name', 'Gender', 'City', 'Course', 'Subject', 'Marks',
       'Attendance (%)', 'Study_Hours', 'Semester', 'Target'],
      dtype='object')

In [ ]:
df.info() #infromation about the databasic

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      1000 non-null   int64
 1   Name            1000 non-null   object
 2   Gender          1000 non-null   object
 3   City            1000 non-null   object
 4   Course          1000 non-null   object
 5   Subject         1000 non-null   object
 6   Marks           731 non-null    float64
 7   Attendance (%)  1000 non-null   int64
 8   Study_Hours     1000 non-null   float64
 9   Semester        1000 non-null   int64
 10  Target          1000 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 86.1+ KB

In [ ]:
df.describe()

,Student_ID,Marks,Attendance (%),Study_Hours,Semester,Target
count,1000.000000,731.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,67.161423,79.383000,3.457700,3.446000,500.500000
std,288.819436,19.366153,11.208476,1.438628,1.696456,288.819436
min,1.000000,35.000000,60.000000,1.000000,1.000000,1.000000
25%,250.750000,50.000000,70.000000,2.200000,2.000000,250.750000
50%,500.500000,69.000000,79.000000,3.400000,3.000000,500.500000
75%,750.250000,83.000000,89.000000,4.700000,5.000000,750.250000
max,1000.000000,99.000000,99.000000,6.000000,6.000000,1000.000000

**RENAME COLUMNS:**

In [ ]:
# df.rename(columns={"old": "new"})

df.rename(columns={"Marks":"MARKS"})

,Student_ID,Name,Gender,City,Course,Subject,MARKS,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

### **ACCESSING DATA:**

**1)Single Column**

In [ ]:
df["Marks"]

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
995    94.0
996    92.0
997    90.0
998     NaN
999    35.0
Name: Marks, Length: 1000, dtype: float64

**2)Multiple columns**

In [ ]:
df[["Subject", "Marks"]]

       Subject  Marks
0      English    NaN
1      English    NaN
2        Maths    NaN
3     Computer    NaN
4    Economics    NaN
..         ...    ...
995   Computer   94.0
996    Science   92.0
997      Maths   90.0
998  Economics    NaN
999   Computer   35.0

[1000 rows x 2 columns]

**3)Row access**

In [ ]:
df.iloc[0]

Student_ID                1
Name              Student_1
Gender                 Male
City                Kolkata
Course                  BBA
Subject             English
Marks                   NaN
Attendance (%)           77
Study_Hours             3.9
Semester                  6
Target                    1
Name: 0, dtype: object

In [ ]:
df.iloc[0:3]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3

In [1]:
df.iloc[2,6]  #2 for 2nd Row and 6 for 6th Column
df.iloc[3,5]
df.iloc[4,7]
df.iloc[3,4]
df.iloc[5,3]
df.iloc[7,5]

NameError: name 'df' is not defined

**4)Only Single Column**

In [ ]:
df.iloc[:,3]

0        Kolkata
1         Mumbai
2         Mumbai
3         Mumbai
4      Bangalore
         ...
995         Pune
996      Chennai
997        Delhi
998      Kolkata
999      Chennai
Name: City, Length: 1000, dtype: object

### **FILTERING DATA**

In [ ]:
[df["Marks"] > 50]

[0      False
 1      False
 2      False
 3      False
 4      False
        ...
 995     True
 996     True
 997     True
 998    False
 999    False
 Name: Marks, Length: 1000, dtype: bool]

In [ ]:
df[df["Marks"] >= 50]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
16,17,Student_17,Female,Bangalore,BCom,Computer,83.0,84,2.7,6,17
20,21,Student_21,Female,Kolkata,BSc,English,94.0,68,5.0,2,21
23,24,Student_24,Female,Bangalore,BA,Maths,65.0,99,1.1,3,24
24,25,Student_25,Female,Bangalore,BBA,Economics,80.0,69,4.7,6,25
...,...,...,...,...,...,...,...,...,...,...,...
990,991,Student_991,Female,Bangalore,BTech,Computer,92.0,60,5.1,1,991
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998

In [ ]:
df[df["Study_Hours"]<3]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
8,9,Student_9,Male,Bangalore,BTech,Computer,NaN,97,1.1,3,9
9,10,Student_10,Female,Bangalore,BBA,English,NaN,86,2.8,5,10
11,12,Student_12,Male,Delhi,BA,English,NaN,75,2.9,5,12
...,...,...,...,...,...,...,...,...,...,...,...
991,992,Student_992,Female,Delhi,BBA,Economics,47.0,78,1.4,6,992
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

In [ ]:
df[df["Attendance (%)"]>=60]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

In [ ]:
df[(df["Marks"] > 50) & (df["Study_Hours"] < 3)]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
16,17,Student_17,Female,Bangalore,BCom,Computer,83.0,84,2.7,6,17
23,24,Student_24,Female,Bangalore,BA,Maths,65.0,99,1.1,3,24
29,30,Student_30,Female,Mumbai,BCom,Economics,67.0,62,1.3,2,30
31,32,Student_32,Male,Bangalore,BA,Science,72.0,75,1.0,1,32
...,...,...,...,...,...,...,...,...,...,...,...
977,978,Student_978,Female,Delhi,BCom,Maths,55.0,95,1.8,4,978
978,979,Student_979,Female,Pune,BCom,English,97.0,84,2.5,4,979
987,988,Student_988,Female,Delhi,BCom,Economics,83.0,84,2.3,6,988
989,990,Student_990,Female,Mumbai,BA,Science,70.0,68,2.3,6,990
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996

In [ ]:
top10 =df.nlargest(10,"Marks")
top10

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
73,74,Student_74,Female,Chennai,BBA,English,99.0,62,4.2,5,74
104,105,Student_105,Female,Pune,BA,Economics,99.0,84,5.4,6,105
113,114,Student_114,Female,Chennai,BA,Science,99.0,74,4.2,2,114
202,203,Student_203,Male,Kolkata,BSc,Economics,99.0,94,1.4,4,203
223,224,Student_224,Female,Bangalore,BTech,Maths,99.0,91,1.2,2,224
240,241,Student_241,Female,Bangalore,BSc,Computer,99.0,65,1.3,4,241
328,329,Student_329,Female,Delhi,BSc,Economics,99.0,74,3.8,3,329
341,342,Student_342,Female,Chennai,BCom,Maths,99.0,81,3.9,2,342
398,399,Student_399,Female,Mumbai,BCom,Computer,99.0,75,5.1,5,399

In [ ]:
top20=df.nlargest(20,"Semester")
top20

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
5,6,Student_6,Female,Chennai,BTech,Maths,NaN,83,4.9,6,6
16,17,Student_17,Female,Bangalore,BCom,Computer,83.0,84,2.7,6,17
24,25,Student_25,Female,Bangalore,BBA,Economics,80.0,69,4.7,6,25
33,34,Student_34,Female,Mumbai,BBA,Science,49.0,94,1.1,6,34
38,39,Student_39,Male,Bangalore,BA,Computer,72.0,90,1.2,6,39
44,45,Student_45,Female,Bangalore,BSc,Science,40.0,60,1.4,6,45
50,51,Student_51,Male,Kolkata,BA,Computer,NaN,84,2.6,6,51
51,52,Student_52,Female,Delhi,BA,Maths,75.0,79,1.3,6,52
65,66,Student_66,Female,Delhi,BCom,Science,63.0,86,5.6,6,66
71,72,Student_72,Female,Mumbai,BSc,Economics,47.0,99,1.7,6,72
80,81,Student_81,Male,Delhi,BTech,Computer,70.0,96,4.0,6,81
86,87,Student_87,Female,Bangalore,BBA,Computer,82.0,60,2.4,6,87
89,90,Student_90,Female,Delhi,BTech,Science,47.0,70,5.3,6,90
94,95,Student_95,Female,Kolkata,BSc,Economics,61.0,72,2.2,6,95
100,101,Student_101,Male,Pune,BSc,Maths,NaN,90,1.4,6,101
104,105,Student_105,Female,Pune,BA,Economics,99.0,84,5.4,6,105
114,115,Student_115,Male,Kolkata,BTech,Maths,NaN,76,2.5,6,115
116,117,Student_117,Male,Delhi,BA,Maths,75.0,97,5.8,6,117
119,120,Student_120,Male,Bangalore,BCom,Science,85.0,67,2.0,6,120

In [ ]:
l=df.nsmallest(5,"Study_Hours")
l

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
31,32,Student_32,Male,Bangalore,BA,Science,72.0,75,1.0,1,32
63,64,Student_64,Male,Kolkata,BCom,English,40.0,82,1.0,1,64
98,99,Student_99,Female,Kolkata,BBA,Science,54.0,68,1.0,5,99
184,185,Student_185,Male,Chennai,BCom,Economics,56.0,63,1.0,1,185
384,385,Student_385,Male,Kolkata,BA,Computer,NaN,94,1.0,2,385

In [ ]:
low=df.nsmallest(10,"Marks")
low

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
96,97,Student_97,Female,Delhi,BA,Economics,35.0,87,1.3,5,97
105,106,Student_106,Female,Kolkata,BTech,Computer,35.0,71,2.4,3,106
139,140,Student_140,Male,Delhi,BTech,Computer,35.0,81,2.5,6,140
208,209,Student_209,Female,Kolkata,BBA,Maths,35.0,88,1.5,1,209
347,348,Student_348,Female,Bangalore,BBA,Maths,35.0,89,3.4,1,348
427,428,Student_428,Female,Delhi,BTech,Computer,35.0,71,3.4,3,428
431,432,Student_432,Female,Delhi,BTech,Maths,35.0,75,3.7,6,432
438,439,Student_439,Male,Kolkata,BCom,Economics,35.0,91,4.1,6,439
507,508,Student_508,Male,Delhi,BBA,Maths,35.0,82,2.6,3,508
633,634,Student_634,Male,Pune,BSc,Science,35.0,98,2.7,3,634

### **DATA CLEANING**

**1)Remove Null Values**

**For Checking Null Values:**

In [ ]:
df.isnull().sum()

Student_ID          0
Name                0
Gender              0
City                0
Course              0
Subject             0
Marks             269
Attendance (%)      0
Study_Hours         0
Semester            0
Target              0
dtype: int64

**A]For all columns**

| Name | Marks | Age |
| ---- | ----- | --- |
| A    | 80    | 20  |
| B    | NaN   | 22  |
| C    | 70    | NaN |

In [ ]:
df.dropna()

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
16,17,Student_17,Female,Bangalore,BCom,Computer,83.0,84,2.7,6,17
20,21,Student_21,Female,Kolkata,BSc,English,94.0,68,5.0,2,21
23,24,Student_24,Female,Bangalore,BA,Maths,65.0,99,1.1,3,24
24,25,Student_25,Female,Bangalore,BBA,Economics,80.0,69,4.7,6,25
...,...,...,...,...,...,...,...,...,...,...,...
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

**RESULT**

| Name | Marks | Age |
| ---- | ----- | --- |
| A    | 80    | 20  |

**B]DROP IF ALL VALUES ARE NULL**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df.dropna(how='all') # it remove that rows who all columnis null

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

**C]Drop based on specific column**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df.dropna(subset=["Marks"]) #remove the row who marks column is empty

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
16,17,Student_17,Female,Bangalore,BCom,Computer,83.0,84,2.7,6,17
20,21,Student_21,Female,Kolkata,BSc,English,94.0,68,5.0,2,21
23,24,Student_24,Female,Bangalore,BA,Maths,65.0,99,1.1,3,24
24,25,Student_25,Female,Bangalore,BBA,Economics,80.0,69,4.7,6,25
...,...,...,...,...,...,...,...,...,...,...,...
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

**D]Drop columns instead of rows**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df.dropna(axis=1)

,Student_ID,Name,Gender,City,Course,Subject,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,65,1.5,2,1000

**E]DROPPING column only if ALL values are null**

In [ ]:
df.dropna(axis=1, how='all')

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

**F]DROP SELECTED COLUMN**

In [ ]:
df.drop("Target", axis=1)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2
...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2

**2)Fill Missing Values**

**In this Stage The Blank Values will be filled by 0**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df.fillna(0)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,0.0,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,0.0,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,0.0,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,0.0,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,0.0,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,0.0,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

**Fill specific column**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df["Marks"].fillna(50)

0      50.0
1      50.0
2      50.0
3      50.0
4      50.0
       ...
995    94.0
996    92.0
997    90.0
998    50.0
999    35.0
Name: Marks, Length: 1000, dtype: float64

**Fill with mean**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df["Marks"].fillna(df["Marks"].mean())

0      67.161423
1      67.161423
2      67.161423
3      67.161423
4      67.161423
         ...
995    94.000000
996    92.000000
997    90.000000
998    67.161423
999    35.000000
Name: Marks, Length: 1000, dtype: float64

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df["Marks"].fillna(df["Marks"].mode())

0      96.0
1       NaN
2       NaN
3       NaN
4       NaN
       ...
995    94.0
996    92.0
997    90.0
998     NaN
999    35.0
Name: Marks, Length: 1000, dtype: float64

### **3)Removing Duplicates**

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Dataset - Dataset.csv")
df.drop_duplicates()

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

**Remove duplicates based on column**

In [ ]:
df.drop_duplicates(subset=["City"])

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
5,6,Student_6,Female,Chennai,BTech,Maths,NaN,83,4.9,6,6
11,12,Student_12,Male,Delhi,BA,English,NaN,75,2.9,5,12
14,15,Student_15,Female,Pune,BBA,Economics,NaN,83,2.5,5,15

### **DATA ANALYSIS**

In [ ]:
df["Marks"].mean()

np.float64(67.16142270861833)

In [ ]:
df["Marks"].max()

99.0

In [ ]:
df["Marks"].min()

35.0

### **MODIFY DATA**

**1)Add new column**

In [ ]:
df["total"] = df["Marks"] + 10
df["total"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...
995    104.0
996    102.0
997    100.0
998      NaN
999     45.0
Name: total, Length: 1000, dtype: float64

In [ ]:
df["Attend"] = df["Attendance (%)"] -50
df["Attend"]
df

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,total,Attend,New target,semester
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,10,1,NaN,27,1,10.0
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2,NaN,49,4,NaN
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3,NaN,42,9,NaN
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4,NaN,21,16,NaN
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5,NaN,17,25,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996,104.0,49,992016,NaN
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997,102.0,27,994009,NaN
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998,100.0,43,996004,NaN
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,10,999,NaN,34,998001,10.0
999,1000,Student_1000,Male,Chennai,BA,Computer,40.0,65,1.5,2,1000,45.0,15,1000000,NaN

In [ ]:
df["New target"] = df["Target"] * df["Target"]
df["New target"]

0            1
1            4
2            9
3           16
4           25
        ...
995     992016
996     994009
997     996004
998     998001
999    1000000
Name: New target, Length: 1000, dtype: int64

**2)Update new Values:**

In [ ]:
df.loc[df["Semester"]>5, "Semester"] = 10

In [ ]:
# df.loc[condition, "marks"]

df.loc[df["Marks"] < 40, "Marks"] = 40

In [ ]:
df.loc[df["City"]=="Mumbai","City"]="Navi Mumbai"

| Name | Marks |
| ---- | ----- |
| A    | 80    |
| B    | 35    |
| C    | 20    |
| D    | 60    |

**AFTER CODE**

| Name | Marks |
| ---- | ----- |
| A    | 80    |
| B    | 40    |
| C    | 40    |
| D    | 60    |

### **SORTING DATA**

In [ ]:
df.sort_values("Marks")

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,total,Attend,New target,semester
999,1000,Student_1000,Male,Chennai,BA,Computer,40.0,65,1.5,2,1000,45.0,15,1000000,NaN
981,982,Student_982,Female,Bangalore,BA,Economics,40.0,75,5.5,2,982,50.0,25,964324,NaN
969,970,Student_970,Male,Bangalore,BSc,Maths,40.0,94,5.6,1,970,50.0,44,940900,NaN
43,44,Student_44,Female,Mumbai,BCom,Computer,40.0,82,5.0,1,44,47.0,32,1936,NaN
44,45,Student_45,Female,Bangalore,BSc,Science,40.0,60,1.4,10,45,50.0,10,2025,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,981,Student_981,Female,Bangalore,BA,Maths,NaN,84,2.5,5,981,NaN,34,962361,NaN
984,985,Student_985,Female,Delhi,BTech,English,NaN,78,1.2,1,985,NaN,28,970225,NaN
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,10,993,NaN,42,986049,10.0
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,10,995,NaN,25,990025,10.0
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,10,999,NaN,34,998001,10.0

**Descending Order:**

In [ ]:
df.sort_values("Marks", ascending=False)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,total,Attend,New target,semester
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16,109.0,23,256,NaN
959,960,Student_960,Male,Delhi,BCom,Science,99.0,84,2.3,1,960,109.0,34,921600,NaN
73,74,Student_74,Female,Chennai,BBA,English,99.0,62,4.2,5,74,109.0,12,5476,NaN
113,114,Student_114,Female,Chennai,BA,Science,99.0,74,4.2,2,114,109.0,24,12996,NaN
104,105,Student_105,Female,Pune,BA,Economics,99.0,84,5.4,10,105,109.0,34,11025,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,981,Student_981,Female,Bangalore,BA,Maths,NaN,84,2.5,5,981,NaN,34,962361,NaN
984,985,Student_985,Female,Delhi,BTech,English,NaN,78,1.2,1,985,NaN,28,970225,NaN
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,10,993,NaN,42,986049,10.0
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,10,995,NaN,25,990025,10.0
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,10,999,NaN,34,998001,10.0

**Sort by multiple columns**

In [ ]:
df.sort_values(["Marks", "Study_Hours"], ascending=False)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,total,Attend,New target,semester
738,739,Student_739,Male,Mumbai,BA,English,99.0,78,5.9,5,739,109.0,28,546121,NaN
525,526,Student_526,Male,Chennai,BCom,Science,99.0,91,5.5,3,526,109.0,41,276676,NaN
104,105,Student_105,Female,Pune,BA,Economics,99.0,84,5.4,10,105,109.0,34,11025,10.0
398,399,Student_399,Female,Mumbai,BCom,Computer,99.0,75,5.1,5,399,109.0,25,159201,NaN
73,74,Student_74,Female,Chennai,BBA,English,99.0,62,4.2,5,74,109.0,12,5476,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,282,Student_282,Female,Mumbai,BA,Maths,NaN,76,1.1,10,282,NaN,26,79524,10.0
444,445,Student_445,Female,Pune,BA,Maths,NaN,75,1.1,3,445,NaN,25,198025,NaN
384,385,Student_385,Male,Kolkata,BA,Computer,NaN,94,1.0,2,385,NaN,44,148225,NaN
744,745,Student_745,Male,Mumbai,BBA,Computer,NaN,92,1.0,2,745,NaN,42,555025,NaN
897,898,Student_898,Female,Bangalore,BBA,Computer,NaN,87,1.0,4,898,NaN,37,806404,NaN

### **GROUPING DATA**

In [ ]:
df.groupby("Course")["Marks"].mean()

Course
BA       67.880503
BBA      67.440789
BCom     67.757764
BSc      68.343284
BTech    65.408000
Name: Marks, dtype: float64

### **DataFrame**
Table

In [ ]:
df = pd.DataFrame({
    "name": ["A", "B"],
    "marks": [80, 90]
})
df

  name  marks
0    A     80
1    B     90

In [ ]:
df = pd.DataFrame({
    "id": [2,3,4],
    "city": ["mumbai","pune","chhenai"],
    "subject": ["math","hindi","english"]
})
df

   id     city  subject
0   2   mumbai     math
1   3     pune    hindi
2   4  chhenai  english

### **MERGING DATA**

In [ ]:
df1 = pd.DataFrame({
    "id": [1, 2, 3],
    "name": ["A", "B", "C"]
})
df1

   id name
0   1    A
1   2    B
2   3    C

In [ ]:
df2 = pd.DataFrame({
    "id": [2, 3, 4],
    "marks": [80, 90, 100]
})
df2

   id  marks
0   2     80
1   3     90
2   4    100

In [ ]:
pd.merge(df1, df2, on="id")

   id name  marks
0   2    B     80
1   3    C     90

### **COUNTING**

In [ ]:
df = pd.read_csv("/content/Dataset - Dataset.csv")
df["City"].value_counts()

City
Mumbai       178
Bangalore    177
Delhi        174
Kolkata      170
Pune         168
Chennai      133
Name: count, dtype: int64

### **unique() and nunique()**

**Counts Unique values in Column**

In [ ]:
df["Marks"].unique()

array([nan, 99., 83., 94., 65., 80., 39., 67., 72., 61., 49., 95., 55.,
       40., 96., 47., 37., 42., 78., 75., 50., 82., 90., 98., 52., 53.,
       89., 38., 63., 77., 68., 73., 43., 71., 70., 76., 56., 35., 54.,
       69., 92., 85., 74., 57., 58., 97., 41., 64., 48., 36., 46.])

**Counts Total of Unique Values:**

In [ ]:
df["Marks"].nunique()

50

### **EXPORTING DATA**

In [ ]:
df.to_csv("output.csv")

### **PRACTICE QUESTIONS**

Q1) Read CSV and display first 5 rows

Q2) Find average marks

Q3) Filter students with marks > 50

Q4) Add new column “bonus marks”

Q5) Sort data by marks