In [ ]:
import pandas as pd

  ***Anwar Question***

In [ ]:
# Q1. Read CSV and display last rows
df= pd.read_csv("/content/Dataset - Dataset.csv")
df.tail(10)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
990,991,Student_991,Female,Bangalore,BTech,Computer,92.0,60,5.1,1,991
991,992,Student_992,Female,Delhi,BBA,Economics,47.0,78,1.4,6,992
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,6,993
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

In [ ]:
# Q2. Find Max Marks
df["Marks"].max()

99.0

In [ ]:
# Q3. Filter student with >60
df["Marks"]>60

0      False
1      False
2      False
3      False
4      False
       ...
995     True
996     True
997     True
998    False
999    False
Name: Marks, Length: 1000, dtype: bool

In [ ]:
# Q4. Add new column "new target"
df["New target"]=df["Target"]+30
df["New target"]

0        31
1        32
2        33
3        34
4        35
       ...
995    1026
996    1027
997    1028
998    1029
999    1030
Name: New target, Length: 1000, dtype: int64

***Krit Question***

In [ ]:
# Q1.Read excel and display last(10)
df=pd.read_excel("/content/Dataset.xlsx")
df.tail(10)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
990,991,Student_991,Female,Bangalore,BTech,Computer,92.0,60,5.1,1,991
991,992,Student_992,Female,Delhi,BBA,Economics,47.0,78,1.4,6,992
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,6,993
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000

In [ ]:
# Q2.Find mean of marks
df["Marks"].mean()

np.float64(67.16142270861833)

In [ ]:
# Q3.Create multiple column with subsem.
df[["Subject","Semester"]]

       Subject  Semester
0      English         6
1      English         3
2        Maths         2
3     Computer         4
4    Economics         2
..         ...       ...
995   Computer         3
996    Science         2
997      Maths         5
998  Economics         6
999   Computer         2

[1000 rows x 2 columns]

In [ ]:
# Q4.Filter the Marks>80
df[df["Marks"] >= 80]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
16,17,Student_17,Female,Bangalore,BCom,Computer,83.0,84,2.7,6,17
20,21,Student_21,Female,Kolkata,BSc,English,94.0,68,5.0,2,21
24,25,Student_25,Female,Bangalore,BBA,Economics,80.0,69,4.7,6,25
34,35,Student_35,Female,Kolkata,BA,English,95.0,71,2.0,5,35
...,...,...,...,...,...,...,...,...,...,...,...
990,991,Student_991,Female,Bangalore,BTech,Computer,92.0,60,5.1,1,991
993,994,Student_994,Female,Mumbai,BSc,Computer,92.0,93,3.5,3,994
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998

***Shivam Question***

In [ ]:
# Q1.What does info method do?
df.info()
# It given the short info of xlsx files

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      1000 non-null   int64
 1   Name            1000 non-null   object
 2   Gender          1000 non-null   object
 3   City            1000 non-null   object
 4   Course          1000 non-null   object
 5   Subject         1000 non-null   object
 6   Marks           731 non-null    float64
 7   Attendance (%)  1000 non-null   int64
 8   Study_Hours     1000 non-null   float64
 9   Semester        1000 non-null   int64
 10  Target          1000 non-null   int64
dtypes: float64(2), int64(4), object(5)
memory usage: 86.1+ KB

In [ ]:
# Q2.what is the difference betwen the .loc and .iloc?
df.iloc[0] # it use for access the rows in pandas
df.loc[df["Marks"]<40,"Marks"]=40 # it change the value basic on contaions

In [ ]:
# Q3.What is the difference betwen drop and dropna?
df.dropna(how="all")
df.drop("Study_Hours", axis=1) # it drop

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,10,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,10,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,10,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,10,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,10,2,5
...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,40.0,10,3,996
996,997,Student_997,Male,Chennai,BA,Science,40.0,10,2,997
997,998,Student_998,Female,Delhi,BSc,Maths,40.0,10,5,998
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,10,6,999
999,1000,Student_1000,Male,Chennai,BA,Computer,40.0,10,2,1000

In [ ]:
# Q4.Read CSV and display first 5 rows.
df=pd.read_csv("/content/Dataset - Dataset.csv")
df.head(5)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1
1,2,Student_2,Female,Mumbai,BTech,English,NaN,99,1.3,3,2
2,3,Student_3,Male,Mumbai,BBA,Maths,NaN,92,5.2,2,3
3,4,Student_4,Male,Mumbai,BCom,Computer,NaN,71,1.9,4,4
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5

***Mahi Question***

In [ ]:
# Q1.Access the 4 to 10 row
df.iloc[4:11]

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
4,5,Student_5,Male,Bangalore,BSc,Economics,NaN,67,4.6,2,5
5,6,Student_6,Female,Chennai,BTech,Maths,NaN,83,4.9,6,6
6,7,Student_7,Male,Bangalore,BCom,Maths,NaN,75,4.6,5,7
7,8,Student_8,Male,Chennai,BCom,Computer,NaN,63,3.9,1,8
8,9,Student_9,Male,Bangalore,BTech,Computer,NaN,97,1.1,3,9
9,10,Student_10,Female,Bangalore,BBA,English,NaN,86,2.8,5,10
10,11,Student_11,Male,Kolkata,BCom,Computer,NaN,68,4.0,4,11

In [ ]:
# Q2.Get unigue values on subject column.
df["Subject"].unique()

array(['English', 'Maths', 'Computer', 'Economics', 'Science'],
      dtype=object)

In [ ]:
# Q3.Add new column and calcuate the total StudyHoues.
df["Total Study Hours"]=df["Study_Hours"]+df["Study_Hours"]
df["Total Study Hours"]

0       7.8
1       2.6
2      10.4
3       3.8
4       9.2
       ...
995     4.6
996     6.4
997    12.0
998     4.2
999     3.0
Name: Total Study Hours, Length: 1000, dtype: float64

In [ ]:
# Q4.Caluclate the makes of each subjects
df.groupby("Subject")["Marks"].sum()

Subject
Computer     10476.0
Economics    10233.0
English      10044.0
Maths         9881.0
Science       8461.0
Name: Marks, dtype: float64

***Shreya Question***

In [ ]:
# Q1.Sort column semesterin ascending order
df.sort_values("Semester")

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,Total Study Hours
990,991,Student_991,Female,Bangalore,BTech,Computer,92.0,60,5.1,1,991,10.2
984,985,Student_985,Female,Delhi,BTech,English,NaN,78,1.2,1,985,2.4
933,934,Student_934,Male,Mumbai,BSc,Science,47.0,92,1.1,1,934,2.2
943,944,Student_944,Male,Chennai,BSc,Economics,67.0,86,3.2,1,944,6.4
43,44,Student_44,Female,Mumbai,BCom,Computer,37.0,82,5.0,1,44,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...
359,360,Student_360,Male,Delhi,BBA,Maths,NaN,97,2.0,6,360,4.0
361,362,Student_362,Male,Pune,BBA,English,NaN,74,2.0,6,362,4.0
5,6,Student_6,Female,Chennai,BTech,Maths,NaN,83,4.9,6,6,9.8
0,1,Student_1,Male,Kolkata,BBA,English,NaN,77,3.9,6,1,7.8
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995,5.0

In [ ]:
# Q2.Find the average Attendance (%)
df["Attendance (%)"].mean()

np.float64(79.383)

In [ ]:
# Q3.Fill the null values in the marks column with median
df.fillna(df["Marks"].median())

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,Total Study Hours
0,1,Student_1,Male,Kolkata,BBA,English,69.0,77,3.9,6,1,7.8
1,2,Student_2,Female,Mumbai,BTech,English,69.0,99,1.3,3,2,2.6
2,3,Student_3,Male,Mumbai,BBA,Maths,69.0,92,5.2,2,3,10.4
3,4,Student_4,Male,Mumbai,BCom,Computer,69.0,71,1.9,4,4,3.8
4,5,Student_5,Male,Bangalore,BSc,Economics,69.0,67,4.6,2,5,9.2
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.0,99,2.3,3,996,4.6
996,997,Student_997,Male,Chennai,BA,Science,92.0,77,3.2,2,997,6.4
997,998,Student_998,Female,Delhi,BSc,Maths,90.0,93,6.0,5,998,12.0
998,999,Student_999,Female,Kolkata,BTech,Economics,69.0,84,2.1,6,999,4.2
999,1000,Student_1000,Male,Chennai,BA,Computer,35.0,65,1.5,2,1000,3.0

In [ ]:
#Q4.Drop the column with any null values
df.dropna(axis=1)

,Student_ID,Name,Gender,City,Course,Subject,Attendance (%),Study_Hours,Semester,Target,Total Study Hours
0,1,Student_1,Male,Kolkata,BBA,English,77,3.9,6,1,7.8
1,2,Student_2,Female,Mumbai,BTech,English,99,1.3,3,2,2.6
2,3,Student_3,Male,Mumbai,BBA,Maths,92,5.2,2,3,10.4
3,4,Student_4,Male,Mumbai,BCom,Computer,71,1.9,4,4,3.8
4,5,Student_5,Male,Bangalore,BSc,Economics,67,4.6,2,5,9.2
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,99,2.3,3,996,4.6
996,997,Student_997,Male,Chennai,BA,Science,77,3.2,2,997,6.4
997,998,Student_998,Female,Delhi,BSc,Maths,93,6.0,5,998,12.0
998,999,Student_999,Female,Kolkata,BTech,Economics,84,2.1,6,999,4.2
999,1000,Student_1000,Male,Chennai,BA,Computer,65,1.5,2,1000,3.0

***Siddhi Question***

In [ ]:
# Q1.Sort Marks in descending and Ascending order.
df.sort_values("Marks")
df.sort_values("Marks",ascending=False)

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16
959,960,Student_960,Male,Delhi,BCom,Science,99.0,84,2.3,1,960
73,74,Student_74,Female,Chennai,BBA,English,99.0,62,4.2,5,74
113,114,Student_114,Female,Chennai,BA,Science,99.0,74,4.2,2,114
104,105,Student_105,Female,Pune,BA,Economics,99.0,84,5.4,6,105
...,...,...,...,...,...,...,...,...,...,...,...
980,981,Student_981,Female,Bangalore,BA,Maths,NaN,84,2.5,5,981
984,985,Student_985,Female,Delhi,BTech,English,NaN,78,1.2,1,985
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,6,993
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999

In [ ]:
# Q2.Add any 2 column and add +10
df["New target"]=df["Target"]+10
df["New target"]

0        11
1        12
2        13
3        14
4        15
       ...
995    1006
996    1007
997    1008
998    1009
999    1010
Name: New target, Length: 1000, dtype: int64

In [ ]:
# Q3.Make any 2 column and group it
df.groupby("Subject")["Marks"].sum()

Subject
Computer     10476.0
Economics    10233.0
English      10044.0
Maths         9881.0
Science       8461.0
Name: Marks, dtype: float64

In [ ]:
# Q4.Marge data is bleow
# Table 1
# id=[4.6,7,10]
# name=[A,D,B,Z]
# Table 2
# id=[7,10,11,12]
# name=[C,D,Y,X]
table1=pd.DataFrame({"id":[4,6,7,10],"Table1_name":["A","D","B","Z"]})
table2=pd.DataFrame({"id":[7,10,11,12],"Table2_name":["C","D","Y","X"]})
pd.merge(table1,table2,on="id")

   id Table1_name Table2_name
0   7           B           C
1  10           Z           D

***Shail Question***

In [ ]:
# Q1.Syntax of import & linking the CSV file and excel files
import pandas as pd
df=pd.read_csv("files-link")

In [ ]:
# Q2.Show All null as values
df.isnull().sum()

Student_ID          0
Name                0
Gender              0
City                0
Course              0
Subject             0
Marks             269
Attendance (%)      0
Study_Hours         0
Semester            0
Target              0
New target          0
dtype: int64

In [ ]:
# Q3.How to modified data and add new column
df.fillna(df["Marks"].mean())

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,New target
0,1,Student_1,Male,Kolkata,BBA,English,67.161423,77,3.9,6,1,11
1,2,Student_2,Female,Mumbai,BTech,English,67.161423,99,1.3,3,2,12
2,3,Student_3,Male,Mumbai,BBA,Maths,67.161423,92,5.2,2,3,13
3,4,Student_4,Male,Mumbai,BCom,Computer,67.161423,71,1.9,4,4,14
4,5,Student_5,Male,Bangalore,BSc,Economics,67.161423,67,4.6,2,5,15
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Student_996,Male,Pune,BCom,Computer,94.000000,99,2.3,3,996,1006
996,997,Student_997,Male,Chennai,BA,Science,92.000000,77,3.2,2,997,1007
997,998,Student_998,Female,Delhi,BSc,Maths,90.000000,93,6.0,5,998,1008
998,999,Student_999,Female,Kolkata,BTech,Economics,67.161423,84,2.1,6,999,1009
999,1000,Student_1000,Male,Chennai,BA,Computer,35.000000,65,1.5,2,1000,1010

In [ ]:
# Q4.Make table in Asc and Dec order
df.sort_values("Marks", ascending=False)
df.sort_values("Marks")

,Student_ID,Name,Gender,City,Course,Subject,Marks,Attendance (%),Study_Hours,Semester,Target,New target
15,16,Student_16,Male,Delhi,BA,Maths,99.0,73,2.3,3,16,26
959,960,Student_960,Male,Delhi,BCom,Science,99.0,84,2.3,1,960,970
73,74,Student_74,Female,Chennai,BBA,English,99.0,62,4.2,5,74,84
113,114,Student_114,Female,Chennai,BA,Science,99.0,74,4.2,2,114,124
104,105,Student_105,Female,Pune,BA,Economics,99.0,84,5.4,6,105,115
...,...,...,...,...,...,...,...,...,...,...,...,...
980,981,Student_981,Female,Bangalore,BA,Maths,NaN,84,2.5,5,981,991
984,985,Student_985,Female,Delhi,BTech,English,NaN,78,1.2,1,985,995
992,993,Student_993,Female,Bangalore,BA,Computer,NaN,92,5.3,6,993,1003
994,995,Student_995,Female,Bangalore,BSc,Science,NaN,75,2.5,6,995,1005
998,999,Student_999,Female,Kolkata,BTech,Economics,NaN,84,2.1,6,999,1009

***Small project***

In [ ]:
import random

def play_game():
    # 1. Define choices
    choices = ['s', 'p', 'r']

    print("--- Stone, Paper, Scissors Game ---")
    print("Rules: 's' for Stone, 'p' for Paper, 'r' for Scissors")

    # 2. Get user input
    user_choice = input("Enter your choice (s/p/r): ").lower()

    if user_choice not in choices:
        print("Invalid choice! Please restart and pick 's', 'p', or 'r'.")
        return

    # 3. Computer's choice
    computer_choice = random.choice(choices)
    print(f"Computer chose: {computer_choice}")

    # 4. Determine result
    if user_choice == computer_choice:
        print("It's a Tie!")

    elif (user_choice == 's' and computer_choice == 'r') or \
         (user_choice == 'p' and computer_choice == 's') or \
         (user_choice == 'r' and computer_choice == 'p'):
        print("You Win!")

    else:
        print("You Lose!")

# Run the game
play_game()

--- Stone, Paper, Scissors Game ---
Rules: 's' for Stone, 'p' for Paper, 'r' for Scissors
Enter your choice (s/p/r): P
Computer chose: p
It's a Tie!

In [1]:
import random

def game():
  print("Start of game enter start or exit below")
  start_input=input("Enter your chose ")
  if(start_input=="start"):
    print("Game started")
    while True:
      choices = ['s', 'p', 'r']
      print("\n--- Stone, Paper, Scissors Game ---")
      print("Rules: 's' for Stone, 'p' for Paper, 'r' for Scissors")
      # 2. Get user input
      user_choice = input("Enter your choice (s/p/r): ").lower()

      if user_choice not in choices:
        if user_choice == "start":
          print("Game started")
          continue
        if user_choice == "exit":
          print("Game exit")
          break
      else:
        print("Invalid choice! Please restart and pick 's', 'p', or 'r'.")

      # 3. Computer's choice
      computer_choice = random.choice(choices)
      if (computer_choice == "s"):
        print("Computer chose: Stone")
      elif (computer_choice == "p"):
        print("Computer chose: Paper")
      else:
        print("Computer chose: Scissors")

      # 4. Determine result
      if user_choice == computer_choice:
          print("It's a Tie!")

      elif (user_choice == 's' and computer_choice == 'r') or \
          (user_choice == 'p' and computer_choice == 's') or \
          (user_choice == 'r' and computer_choice == 'p'):
          print("You Win!")

      else:
          print("You Lose!")
  else:
    print("Game exit")
    return

game()

Start of game enter start or exit below
Enter your chose start
Game started

--- Stone, Paper, Scissors Game ---
Rules: 's' for Stone, 'p' for Paper, 'r' for Scissors
Enter your choice (s/p/r): p
Invalid choice! Please restart and pick 's', 'p', or 'r'.
Computer chose: s
You Win!

--- Stone, Paper, Scissors Game ---
Rules: 's' for Stone, 'p' for Paper, 'r' for Scissors
Enter your choice (s/p/r): s
Invalid choice! Please restart and pick 's', 'p', or 'r'.
Computer chose: p
You Lose!

--- Stone, Paper, Scissors Game ---
Rules: 's' for Stone, 'p' for Paper, 'r' for Scissors
Enter your choice (s/p/r): exit
Game exit